#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : textdistance
Version  : 4.2.2
Release  : 13
URL      : https://files.pythonhosted.org/packages/11/b9/f1f307bf32749043bc7335ec97fa4e917b2465f8c18589735cdc5a0db329/textdistance-4.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/11/b9/f1f307bf32749043bc7335ec97fa4e917b2465f8c18589735cdc5a0db329/textdistance-4.2.2.tar.gz
Summary  : Compute distance between the two texts.
Group    : Development/Tools
License  : MIT
Requires: textdistance-license = %{version}-%{release}
Requires: textdistance-python = %{version}-%{release}
Requires: textdistance-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
![TextDistance logo](logo.png)

%package license
Summary: license components for the textdistance package.
Group: Default

%description license
license components for the textdistance package.


%package python
Summary: python components for the textdistance package.
Group: Default
Requires: textdistance-python3 = %{version}-%{release}

%description python
python components for the textdistance package.


%package python3
Summary: python3 components for the textdistance package.
Group: Default
Requires: python3-core
Provides: pypi(textdistance)

%description python3
python3 components for the textdistance package.


%prep
%setup -q -n textdistance-4.2.2
cd %{_builddir}/textdistance-4.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641409853
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/textdistance
cp %{_builddir}/textdistance-4.2.2/LICENSE %{buildroot}/usr/share/package-licenses/textdistance/1cd37cfcc5e8192f596e3a6bbef042ec23d05ce8
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/textdistance/1cd37cfcc5e8192f596e3a6bbef042ec23d05ce8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
